### ISSUE TITLE
Gotify support

### ISSUE THREAD

**Issue by REijkelenberg** [dockupdater/dockupdater#20]
**Describe the bug**
First of all: Thank you for developing Dockupdater! It has been working great so far, except for one small bug. It seems that Apprise does not support Gotify, while (according to its docs) it should. Maybe an outdated version of Apprise is being used? Support for Gotify has only been added [a couple of weeks ago](https://github.com/caronc/apprise/issues/23). For the record, here's [a link](https://github.com/caronc/apprise/wiki/Notify_gotify) to the Apprise documentation regarding Gotify.

Relevant snippet of the log:
`ERROR : Apprise : Unsupported schema ********tifys.`
`ERROR : Apprise : Failed to load notification url: ********tifys://********uDy99`
`ERROR : notifiers : Could not add notifier ********tifys://********uDy99`

**Expected behavior**
The ability to send notifications to a Gotify server.

**Technical details:**
* Dockupdater version: 0.7.0
* Docker version: 1.3.9
* Platform (windows/linux): Ubuntu Server 18.04.2 LTS

**Comment by mathcantin** [comment]
I will update apprise package (0.5 to 0.7) later today, I think that will fix this.

**Comment by REijkelenberg** [comment]
Hey,
For testing, I forked your repo and [modified](https://github.com/REijkelenberg/dockupdater/blob/master/requirements.txt) the `requirements.txt` file. I changed `apprise>=0.5.2` to `apprise>=0.7.5`, and it indeed seems to solve the issue. As far a I can tell, Dockupdater is running stable (although I didn't do any extensive testing).

**Comment by mathcantin** [comment]
I release the version 0.7.1 with the latest apprise. https://github.com/dockupdater/dockupdater/releases/tag/0.7.1

**Comment by REijkelenberg** [comment]
Great; thank you for your effort!
